# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 159815cc37c235369d1c0474ac12eb41d1da7b399e20d32c92e4f77c8c1e07010d7ff48e8a9e6646dc789ab55de8c648edcff03ea4cdf86210df85feac2fc175

test:
  secret_key_base: 676b8094933d849f5d86a6468d3e0b5855966b72a45ea6ddf1878bb35695af385d0112b1eeaf3d2340b7acecd76773011566102885748ed2244e976a87a3d62a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
